apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    componet: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      tier: app
  # pod definition
  template:
    metadata:
      labels:
        component: backend
        tier: app
        project: expense
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1.0
        envFrom:
        - configMapRef:
            name: backend
            
    
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    tier: app
    project: expense
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port